[package]
name = "bcm2711-hal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aarch64-cpu = "9.3.1"
embedded-hal = "0.2.7"
nb = "1.1.0"
bcm2711-pac = { path = "../bcm2711-pac" }
